### ISSUE TITLE
False alerts detected? 

### ISSUE THREAD

**Issue by moivica** [jfrog/log4j-tools#12]
Script scan_log4j_calls_jar.py  provided next output: 

```Processing .jar file:
BOOT-INF/lib/commons-logging-1.2.jar

Class: org/apache/commons/logging/impl/Log4JLogger
Vulnerable call | Methods
----------------+---------
log             | error, debug, trace, warn, fatal, info

Processing .jar file:
BOOT-INF/lib/jboss-logging-3.4.1.Final.jar

Class: org/jboss/logging/Log4jLogger
Vulnerable call | Methods
----------------+---------
log             | doLogf, doLog

Processing .jar file:
BOOT-INF/lib/spring-boot-2.4.3.jar

Class: org/springframework/boot/logging/log4j2/ColorConverter
Vulnerable call | Methods
----------------+---------
error           | newInstance
``` 

I've found those methods in project dependencies,  but we don't have log4j-core.jar anywhere in our project (checked the source code and deployed app.jar).  
I've asked dev to check, and they said it is a false positive.

Now i'm not sure is app vulnerable or i'm doing something wrong?

**Comment by ilya-k-1** [comment]
Hi @moivica ,
The tool you ran (scan_log4j_calls) looks for calls to the vulnerable functions in your code. In your case, such calls were found in third party libraries (and not your 1st party code). This may still be problematic if 1) those libraries are used (in a way which may invoke log4j it's only one of the possible logging mechanisms) and 2) there is a vulnerable version of log4j library in your product. In order to help answer the second question, I'd recommend running the tool for detecting the versions of log4j code (scan_log4j_versions.py) as well, because absence of log4j-core.jar does not guarantee that the library code is not there - it may still be present as a jar inside jar, or as separate class files inside another jar file.

**Comment by ilya-k-1** [comment]
Just to clarify, these are not false alerts in the sense that the calls are really present in the code. it's only that additional information is required to interpret the situation as vulnerable/not vulnerable

**Comment by moivica** [comment]
Hello @ilya-k-1  ! 
Thank you for the info! i'll try with `scan_log4j_versions.py` script. 

If i understood this correctly - the flow is: 
Scan for vulnerable versions with scan_log4j_versions script.  If there's no output, the app is not vulnerable. 
If vulnerable version exist, app is definitely vulnerable.
 
Only when vulnerable version is confirmed we can run the script for finding vulnerable methods  (`scan_log4j_calls_jar`) ? 
The 2nd script is handy for exploiting or for incident analysis (we can quickly find possible entry points) but it should not be used to determine is app vulnerable or not?

**Comment by ilya-k-1** [comment]
Hi @moivica ,
Yes, you are right: if `scan_log4j_versions` doesn't output any findings, there should not be a problem. If it does, the recommendation is to try to upgrade anyway due to the severity of this vulnerability.
For the cases upgrading costly or impossible in the near term, `scan_log4j_calls` provides info for further investigation on where exactly the vulnerable library is used. Further investigation may show that these places in the code cannot be reached or do not receive data controlled by a potential attacker, which would mean that the vulnerability is not exploitable, but this kind of investigation needs to be performed carefully.

You can find some more info here:
https://jfrog.com/log4j-log4shell-resources/

**Comment by moivica** [comment]
Thank you very much for your help and clarification.
